import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the Spotify slice
const initialState = {
    userToken: {},          // Holds the user's Spotify access token
    tracks: [],             // Holds the list of tracks
    markets: [],            // Holds the list of available markets/countries
    filteredTracks: [],     // Holds the filtered list of tracks
    popularity: 'none',     // Holds the current popularity filter setting
    country: 'IN',          // Holds the current country filter setting
};

// Define the Spotify slice with reducers
export const spotifySlice = createSlice({
    name: 'Spotify',        // Name of the slice
    initialState,           // Initial state defined above
    reducers: {
        // Reducer to add the user's access token to the state
        addUserToken: (state, action) => {
            state.userToken = action.payload;
        },
        // Reducer to remove the user's access token from the state
        removeUserToken: (state) => {
            state.userToken = {};
        },
        // Reducer to update the list of tracks in the state
        addTrack: (state, action) => {
            state.tracks = action.payload;
        },
        // Reducer to update the list of available markets in the state
        addMarket: (state, action) => {
            state.markets = action.payload;
        },
        // Reducer to update the filtered list of tracks in the state
        addFilteredTracks: (state, action) => {
            state.filteredTracks = action.payload;
        },
        // Reducer to update the current popularity filter setting in the state
        changePopularity: (state, action) => {
            state.popularity = action.payload;
        },
        // Reducer to update the current country filter setting in the state
        changeCountry: (state, action) => {
            state.country = action.payload;
        },
    }
});

// Export actions generated by the Spotify slice
export const { addUserToken, removeUserToken, addTrack, addMarket, addFilteredTracks, changePopularity, changeCountry } = spotifySlice.actions;

// Export the reducer function generated by the Spotify slice
export default spotifySlice.reducer;
